version: "1"
services:
  - type: web
    name: black-friday-sales-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.headless=true --server.enableCORS=false
    repo: https://github.com/Manu040405/Black-friday-sales-prediction
    branch: main
    autoDeploy: true
